In [1]:
# numpy 004
# Advanced indexing and tricks

In [2]:
# import de bibliotecas
import numpy as np

In [3]:
# indexing with array of indices
a = np.arange(12)**2
a

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121])

In [8]:
i = np.array([1, 1, 3, 8, 5])
i

array([1, 1, 3, 8, 5])

In [9]:
# busca os valores na matriz a indexado dos valores da array i
a[i]

array([ 1,  1,  9, 64, 25])

In [10]:
# busca os valores na matriz a indexado dos valores da array j no formato da array j
j = np.array([[3, 4],
             [9, 7]])
a[j]

array([[ 9, 16],
       [81, 49]])

In [11]:
pallete = np.array([[0, 0, 0],        # black
                    [255, 0, 0],      # red 
                    [0, 255, 0],      # green
                    [0, 0, 255],      # blue 
                    [255, 255, 255]]) # white    

In [12]:
image = np.array([[0, 1, 2, 0],
                  [0, 3, 4, 0]])  # cada valor corresponde a uma cor na matriz anterior(pallete)

In [14]:
# forma uma matriz bidimensional com as cores
pallete[image]

array([[[  0,   0,   0],
        [255,   0,   0],
        [  0, 255,   0],
        [  0,   0,   0]],

       [[  0,   0,   0],
        [  0,   0, 255],
        [255, 255, 255],
        [  0,   0,   0]]])

In [22]:
# nova matriz A
a = np.arange(12).reshape(3, 4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [23]:
# indices - matrizes tem q ter mesmo formato
i = np.array([[0, 1],
              [1, 2]])
j = np.array([[2, 1],
              [3, 3]])

In [24]:
#                                                              i, j    i, j    i, j    i, j
# matriz a com os elementos correspondentes de linha x coluna((0, 2), (1, 1), (1, 3), (2, 3))
a[i, j]

array([[ 2,  5],
       [ 7, 11]])

In [25]:
# fixando a coluna em 2
a[i, 2]

array([[ 2,  6],
       [ 6, 10]])

In [26]:
# matriz resultante: 
# m1 => linha 0 da matriz A colunas vindo da matriz j, 
# m2 => linha 1 da matriz A, colunas vindo da matriz j, 
# m3 => linha 2 da matriz A, colunas vindo da matriz j
a[:, j]

array([[[ 2,  1],
        [ 3,  3]],

       [[ 6,  5],
        [ 7,  7]],

       [[10,  9],
        [11, 11]]])