In [1]:
# numpy 002
# Indexing, Slicing, Iterating

In [2]:
import numpy as np

In [3]:
a = np.arange(10)**3
a

array([  0,   1,   8,  27,  64, 125, 216, 343, 512, 729])

In [4]:
# indice 2
a[2]

8

In [5]:
# indice 2 a 5
a[2:5]

array([ 8, 27, 64])

In [8]:
# do inicio ao sexto elemento, set 1000 a cada dois
a[:6:2] = 1000
a

array([1000,    1, 1000,   27, 1000,  125,  216,  343,  512,  729])

In [9]:
a[::-1]

array([ 729,  512,  343,  216,  125, 1000,   27, 1000,    1, 1000])

In [16]:
# raiz cubica dos valores na matriz, acrescentando o round para arredondar
for _ in a:
    print((_**(1/3)).round(2))

10.0
1.0
10.0
3.0
10.0
5.0
6.0
7.0
8.0
9.0


In [24]:
# Com base nos indices de linha e coluna, retorna um valor.
def f(x, y):
    return 10 * (x+y)
# Definimos que usaremos a função f, num formato 5 x 4 e tipo inteiro
b = np.fromfunction(f, (5, 4), dtype=int)
b

array([[ 0, 10, 20, 30],
       [10, 20, 30, 40],
       [20, 30, 40, 50],
       [30, 40, 50, 60],
       [40, 50, 60, 70]])

In [33]:
# elemento linha 2 coluna 3
b[2, 3]

50

In [34]:
# Selecionando a coluna 1
b[0:5, 1]

array([10, 20, 30, 40, 50])

In [36]:
# Selecionando a coluna 1
b[:,1]

array([10, 20, 30, 40, 50])

In [38]:
# selecionando a ultima coluna
b[:, -1]

array([30, 40, 50, 60, 70])

In [39]:
# selecionando duas linhas e todas as colunas
b[1:3, :]

array([[10, 20, 30, 40],
       [20, 30, 40, 50]])

In [41]:
# Selecionando linha 4
b[4, :]

array([40, 50, 60, 70])