In [1]:
# numpy 002

In [2]:
import numpy as np

In [4]:
# criando matriz 1d
a = np.arange(1,6)
a

array([1, 2, 3, 4, 5])

In [8]:
# criando matriz 2d
b = np.arange(1, 13).reshape(4, 3)
b

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [10]:
# criando matriz 3d
c = np.arange(24).reshape(2, 3, 4)
c

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [11]:
# Caso as matrizes sejam muito grandes, o numpy representa a parte do meio com ...

In [12]:
# Operadores

In [13]:
a = np.arange(6)

In [15]:
b = np.array([5, 9, 6, 4, 2, 7])

In [18]:
# Soma
c = a + b

In [17]:
c

array([ 5, 10,  8,  7,  6, 12])

In [19]:
# Exponenciação
b ** 2

array([25, 81, 36, 16,  4, 49])

In [20]:
# booleana retornada em comparações
# compara cada elemento da matriz
b < 5

array([False, False, False,  True,  True, False])